services:

# TODO: mcp bridge to Toolhub router
#  toolhub-{{ namespace.name }}_mcp:
#    image: toolhub-mcp-brige
# etc.

# Toolhub router, only aggregates other hubs
  toolhub-{{ namespace.name }}:
    image: toolhub-twylt:base
    init: false # tini is already in the image# Toolhub router, only aggregates other hubs
    user: {{ namespace.uid }}:{{ namespace.gid }}
    ports:
      - "{{ namespace.port_base }}:3000"
    env_file: {{ namespace.path }}/.env-_router_
    volumes:
    # NOTE: volumes are using special _router_ prefix for data and config storage
      - {{ namespace.path }}/data/_router_:/data
      - {{ namespace.path }}/config/_router_:/config:ro
    read_only: true
    tmpfs:
      - /tmp:rw,nosuid,nodev,size={{ namespace.limits.tmp }},mode=1777
    cap_drop: [ALL]
    security_opt: [no-new-privileges:true]
    pids_limit: {{ namespace.limits.pids }}
    mem_limit: {{ namespace.limits.mem }}
    cpus: {{ namespace.limits.cpu }}

# Toolhubs with certain toolkits
{% for hub in hubs %}
  toolhub-{{ namespace.name }}-{{ hub.name }}:
    image: {{ hub.image }}
    init: false # tini is already in the image
    user: {{ namespace.uid }}:{{ namespace.gid }}
    ports:
      - "{{ namespace.port_base + hub.port }}:3000"
    env_file: {{ namespace.path }}/.env-{{ hub.name }}
    volumes:
      - {{ namespace.path }}/data/{{ hub.name }}:/data
      - {{ namespace.path }}/config/{{ hub.name }}:/config:ro
{% for tool in hub.pack %}
      - {{ namespace.tools }}/{{ tool.toolset }}:/tools/{{ tool.toolset }}:ro
{% endfor %}
{% if hub.get('kind',None) != 'docker' %}
      - {{ namespace.workspace }}:/workspace
{% else %}
      - /var/run/docker.sock:/var/run/docker.sock
{% endif %}
    read_only: true
    tmpfs:
      - /tmp:rw,nosuid,nodev,size={{ hub.limits.tmp or namespace.limits.tmp }},mode=1777
    cap_drop: [ALL]
    security_opt: [no-new-privileges:true]
    pids_limit: {{ hub.limits.pids or namespace.limits.pids }}
    mem_limit: {{ hub.limits.mem or namespace.limits.mem }}
    cpus: {{ hub.limits.cpu or namespace.limits.cpu }}
{% endfor %}
